endpoints:
  frac_schedules:
    enabled: true
    model: api.models.FracSchedule
    ignore_unkown: true
    # exclude:
    #   - start_in
    #   - duration_in_days
    #   - reviewed_by
    #   - risk_assessments
    #   - comments
    #   - last_upload_date
    mappings:
      aliases:
        company: operator
        well_api: api14
        well_name: wellname
        frac_start_date: frac_start_date
        frac_end_date: frac_end_date
        surface_lat: shllat
        surface_long: shllon
        bottomhole_lat: bhllat
        bottomhole_long: bhllon
        tvd: tvd
        target_formation: target_formation
      dates:
        - frac_start_date
        - frac_end_date
